FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy all project files
COPY . .

# Install dependencies, including prometheus_client
RUN pip install --no-cache-dir fastapi uvicorn pymongo kafka-python pydantic prometheus_client

# Expose FastAPI port + Prometheus metrics port
EXPOSE 8000 8001

# Run FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]